CREATE VIEW VIEW_USER_INFORMATION AS 
SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, C1.CITY_NAME AS CURRENT_CITY, C1.STATE_NAME AS CURRENT_STATE, C1.COUNTRY_NAME AS CURRENT_COUNTRY, C2.CITY_NAME AS HOMETOWN_CITY, C2.STATE_NAME AS HOMETOWN_STATE, C2.COUNTRY_NAME AS HOMETOWN_COUNTRY, P.INSTITUTION AS INSTITUTION_NAME, E.PROGRAM_YEAR, P.CONCENTRATION AS PROGRAM_CONCENTRATION, P.DEGREE AS PROGRAM_DEGREE 
FROM USERS U
LEFT JOIN USER_CURRENT_CITIES R ON U.USER_ID = R.USER_ID
LEFT JOIN CITIES C1 ON R.CURRENT_CITY_ID = C1.CITY_ID
LEFT JOIN USER_HOMETOWN_CITIES H ON U.USER_ID = H.USER_ID
LEFT JOIN CITIES C2 ON H.HOMETOWN_CITY_ID = C2.CITY_ID
LEFT JOIN EDUCATION E ON U.USER_ID = E.USER_ID
LEFT JOIN PROGRAMS P ON E.PROGRAM_ID = P.PROGRAM_ID;
CREATE VIEW VIEW_ARE_FRIENDS AS SELECT DISTINCT USER1_ID, USER2_ID FROM FRIENDS;
CREATE VIEW VIEW_PHOTO_INFORMATION AS SELECT DISTINCT A.ALBUM_ID, A.ALBUM_OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME, A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK, A.ALBUM_VISIBILITY, P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK FROM ALBUMS A, PHOTOS P WHERE A.ALBUM_ID = P.ALBUM_ID;
CREATE VIEW VIEW_EVENT_INFORMATION AS SELECT DISTINCT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE, E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE, E.EVENT_ADDRESS, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, E.EVENT_START_TIME, E.EVENT_END_TIME FROM USER_EVENTS E, CITIES C WHERE E.EVENT_CITY_ID = C.CITY_ID;
CREATE VIEW VIEW_TAG_INFORMATION AS SELECT DISTINCT TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y FROM TAGS;